### ISSUE TITLE
退会时崩溃问题

### ISSUE THREAD

**Issue by zhangle1225** [zijingcloud/Android-SDK#18]
* 机型：Alps nb6797_6c_m
* Android系统版本：6.0
* SDK版本:v1.9.3
* 合作伙伴：longshine
* 项目名称：

- [x] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题** 

### 运行代码后复现问题。
退会时程序崩溃
   java.lang.RuntimeException:Camera is being userd after Camera.release() was called
   at android.hardvare.Camera.native_getParameters(Native Method)
   at android.hardware.Camera.getParameters(Camera.java:3125)
   at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1273)
   at android.os.Handler.dispatchMessage(Handler.java:111)
   at android.os.Looper.loop(Looper.java:207)
   at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by 6YingJie** [comment]
C4系统问题，底层在摄像头关掉后，还有线程在getparamter()获取摄像头参数，维海德处理，更新固件即可
