### ISSUE TITLE
入会时紫荆日志写入导致部分手机崩溃

### ISSUE THREAD

**Issue by zhangle1225** [zijingcloud/Android-SDK#21]
* 机型：
* Android系统版本：android 7.0
* SDK版本:  v1.9.5
* Android盒子/手机型号：小米5s 华为荣耀8 华为荣耀10 等手机机型

- [x] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题** 

### Code

错误日志
 com.longshine.ucpdemo:zjvideo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.longshine.ucpdemo:zjvideo, PID: 23484
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.longshine.ucpdemo/com.longshine.longshinelib.view.MyVideoActivity}: java.lang.NullPointerException: Attempt to get length of null array
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2747)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
                                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:163)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6360)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
                                                                                Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                                                   at com.zjrtc.LogcatHelper.initLog(LogcatHelper.java:173)
                                                                                   at com.zjrtc.LogcatHelper.access$000(LogcatHelper.java:21)
                                                                                   at com.zjrtc.LogcatHelper$LogDumper.<init>(LogcatHelper.java:79)
                                                                                   at com.zjrtc.LogcatHelper.start(LogcatHelper.java:58)
                                                                                   at com.zjrtc.ZjVideoActivity.onCreate(ZjVideoActivity.java:48)
                                                                                   at com.longshine.longshinelib.view.MyVideoActivity.onCreate(MyVideoActivity.java:108)
                                                                                   at android.app.Activity.performCreate(Activity.java:6863)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2700)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808) 
                                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:163) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6360) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770) 

### 运行代码后复现问题。
入会时导致部分手机崩溃

**Comment by 6YingJie** [comment]
1.9.7版本已解决
